// Package hosts reconciles a marked, tamp-owned block in the OS hosts file
// with the site hostnames tamp routes. Everything outside the markers is
// another program's or the user's, and tamp never touches it.
//
// The file itself is the boundary: the reconciliation is a pure string
// function, so it is tested against a temp file with no elevation anywhere
// near it.
package hosts

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"

	"github.com/zhide915/tamp/internal/exitcode"
)

// The markers delimiting tamp's block. They are matched as whole lines, so a
// hosts file that merely mentions them in a comment is unaffected.
const (
	BeginMarker = "# --- tamp managed block ---"
	EndMarker   = "# --- end tamp block ---"
)

// Loopback is what every managed hostname resolves to: the router listens
// there, and these names exist only on this machine.
const Loopback = "127.0.0.1"

// blockHeader tells whoever opens the file by hand what rewrites it. Kept as
// lines rather than one string because the terminator is the file's to
// decide, not tamp's.
var blockHeader = []string{
	"# Generated by tamp. 'tamp hosts sync' rewrites everything between these",
	"# two markers; keep your own entries outside them.",
}

// PathVar redirects the file tamp reconciles. It exists for tamp's own tests,
// which must never touch the machine's real hosts file. tamp refuses to
// elevate for a redirected path, so it can only ever reach files the user
// already owns.
const PathVar = "TAMP_HOSTS_FILE"

// OSPath is the operating system's hosts file — the only file the elevated
// half of a sync ever writes, so no environment variable can aim tamp's
// privileges at another one.
func OSPath() string {
	if runtime.GOOS != "windows" {
		return "/etc/hosts"
	}
	root := os.Getenv("SystemRoot")
	if root == "" {
		root = `C:\Windows`
	}
	return filepath.Join(root, "System32", "drivers", "etc", "hosts")
}

// Path is the file this run reconciles: the OS one unless redirected.
// lookupEnv is passed rather than read so the caller keeps the seam.
func Path(lookupEnv func(string) (string, bool)) string {
	if override, ok := lookupEnv(PathVar); ok && override != "" {
		return override
	}
	return OSPath()
}

// Redirected reports whether this run is working on a file other than the
// OS hosts file, which is what forbids elevation.
func Redirected(lookupEnv func(string) (string, bool)) bool {
	return Path(lookupEnv) != OSPath()
}

// Read returns the file's current content. A hosts file that does not exist
// is empty content, not a failure: tamp is about to write one.
func Read(path string) (string, error) {
	body, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return "", nil
	}
	if err != nil {
		return "", &fileFailure{
			reported: exitcode.New(exitcode.CodeFailed,
				fmt.Sprintf("cannot read %s: %v", path, err),
				"check that the file exists and is readable"),
			cause: err,
		}
	}
	return string(body), nil
}

// block renders the hostnames sorted and deduplicated, every line ending the
// way eol says.
func block(entries []string, eol string) string {
	var b strings.Builder
	b.WriteString(BeginMarker + eol)
	for _, line := range blockHeader {
		b.WriteString(line + eol)
	}
	for _, host := range normalize(entries) {
		b.WriteString(Loopback + "  " + host + eol)
	}
	b.WriteString(EndMarker + eol)
	return b.String()
}

// lineEnding is the terminator the rest of the file already uses. Windows
// keeps its hosts file in CRLF, and a block of bare LF lines dropped into one
// would leave the system's own file mixed.
func lineEnding(existing string) string {
	if i := strings.IndexByte(existing, '\n'); i > 0 {
		if existing[i-1] == '\r' {
			return "\r\n"
		}
		return "\n"
	}
	if runtime.GOOS == "windows" {
		return "\r\n"
	}
	return "\n"
}

// Reconcile returns what the file should hold once tamp's block names exactly
// these hostnames. No line outside the block changes; an empty list takes the
// block away entirely, so a removed site's line disappears. A file whose last
// line has no terminator gains one — a marker cannot start a line otherwise —
// and that byte stays behind when the block goes.
func Reconcile(existing string, entries []string) string {
	entries = normalize(entries)
	eol := lineEnding(existing)
	before, after, found := split(existing)

	if !found {
		if len(entries) == 0 {
			return existing
		}
		// A file whose last line has no terminator would otherwise swallow
		// the first marker into it.
		if existing != "" && !strings.HasSuffix(existing, "\n") {
			existing += eol
		}
		return existing + block(entries, eol)
	}
	if len(entries) == 0 {
		return before + after
	}
	return before + block(entries, eol) + after
}

// Resolved lists every hostname the file maps to loopback, sorted, wherever
// the line lives — an entry the user keeps outside tamp's block resolves just
// as well, and "does it resolve" is a different question from "is it in the
// block".
func Resolved(existing string) []string {
	var got []string
	for _, line := range strings.Split(existing, "\n") {
		if comment := strings.IndexByte(line, '#'); comment >= 0 {
			line = line[:comment]
		}
		fields := strings.Fields(line)
		if len(fields) >= 2 && (fields[0] == Loopback || fields[0] == "::1") {
			got = append(got, fields[1:]...)
		}
	}
	return normalize(got)
}

// Entries lists the hostnames tamp's block currently carries, sorted. A file
// with no block has none.
func Entries(existing string) []string {
	before, after, found := split(existing)
	if !found {
		return nil
	}
	body := strings.TrimSuffix(strings.TrimPrefix(existing, before), after)

	var got []string
	for _, line := range strings.Split(body, "\n") {
		fields := strings.Fields(line)
		if len(fields) >= 2 && fields[0] == Loopback {
			got = append(got, fields[1:]...)
		}
	}
	return normalize(got)
}

// split cuts the file around tamp's block: what precedes the begin marker's
// line and what follows the end marker's. found is false when the pair is not
// there, which includes a half-written block — tamp appends a fresh one
// rather than guessing where a lost marker was.
func split(existing string) (before, after string, found bool) {
	begin, ok := lineIndex(existing, 0, BeginMarker)
	if !ok {
		return "", "", false
	}
	end, ok := lineIndex(existing, begin, EndMarker)
	if !ok {
		return "", "", false
	}
	return existing[:begin], existing[endOfLine(existing, end):], true
}

// lineIndex finds the offset of a line equal to want, at or after from.
func lineIndex(s string, from int, want string) (int, bool) {
	for at := from; at <= len(s); {
		stop := endOfLine(s, at)
		if strings.TrimRight(s[at:stop], "\r\n") == want {
			return at, true
		}
		if stop == at {
			break
		}
		at = stop
	}
	return 0, false
}

// endOfLine is the offset just past the line starting at from, terminator
// included.
func endOfLine(s string, from int) int {
	if i := strings.IndexByte(s[from:], '\n'); i >= 0 {
		return from + i + 1
	}
	return len(s)
}

func normalize(entries []string) []string {
	out := slices.Clone(entries)
	slices.Sort(out)
	return slices.Compact(out)
}

// ChangesOnlyTheBlock reports whether replacing current with pending leaves
// every byte outside tamp's markers alone. It is what the elevated half of a
// sync checks before it writes: the privileged step must be able to change
// tamp's block and nothing else, whatever it was handed.
func ChangesOnlyTheBlock(current, pending string) bool {
	return Reconcile(current, Entries(pending)) == pending
}

// Missing names what want holds and have does not, sorted. It is the one
// comparison the hosts block is ever subjected to: run one way it finds the
// entries still to write, and the other way the ones no site claims any more.
func Missing(have, want []string) []string {
	var absent []string
	for _, host := range normalize(want) {
		if !slices.Contains(have, host) {
			absent = append(absent, host)
		}
	}
	return absent
}
