// Package toolchain installs the Python and Node tamp's version matrix pins
// for a Frappe release, into one volume shared by every environment on the
// machine: the same versions provision once and are a no-op after.
package toolchain

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"strings"

	"github.com/zhide915/tamp/internal/engine"
)

const (
	// Volume holds uv, its Pythons, and nvm's Nodes, mounted by every bench
	// container.
	Volume = "tamp-toolchain"

	// Dir is under the bench user's home so that user can write to it.
	Dir = "/home/frappe/.tamp-toolchain"

	// EnvScript is sourced by every command tamp runs in a bench container and
	// by the bench's own processes; it is the one place that locates the
	// shared Pythons and Nodes.
	EnvScript = Dir + "/env.sh"
)

// Request describes one environment's pinned toolchain.
type Request struct {
	Container string
	// Python and Node are matrix versions ("3.11", "18"); uv and nvm resolve
	// them to the newest patch release.
	Python string
	Node   string
	Out    io.Writer
}

// Provision installs the requested Python and Node into the shared volume,
// downloading only what is not already there.
func Provision(ctx context.Context, eng engine.Engine, req Request) error {
	if err := installUV(ctx, eng, req); err != nil {
		return err
	}
	if err := eng.WriteFile(ctx, req.Container, engine.FileSpec{
		Path: EnvScript,
		Data: []byte(envScript()),
		Mode: 0o644,
		UID:  UID,
		GID:  GID,
	}); err != nil {
		return err
	}
	return run(ctx, eng, req, provisionScript, req.Python, req.Node)
}

// installUV places the pinned uv in the shared volume unless that exact
// version is already there. tamp downloads on the host and verifies the
// checksum itself — never `curl | sh` inside the container.
func installUV(ctx context.Context, eng engine.Engine, req Request) error {
	binary := uvPath()
	installed, err := isInstalled(ctx, eng, req.Container, binary)
	if err != nil {
		return err
	}
	if installed {
		return nil
	}

	arch, err := containerArch(ctx, eng, req.Container)
	if err != nil {
		return err
	}
	body, err := fetchUV(ctx, releaseBaseURL, arch)
	if err != nil {
		return err
	}

	// docker cp needs the target directory to already exist.
	if err := run(ctx, eng, req, `set -e; mkdir -p "$(dirname "$1")"`, binary); err != nil {
		return err
	}
	return eng.WriteFile(ctx, req.Container, engine.FileSpec{
		Path: binary,
		Data: body,
		Mode: 0o755,
		UID:  UID,
		GID:  GID,
	})
}

// isInstalled probes for the binary. A probe that could not run is an error,
// not an empty toolchain to fill — engine.Probe draws that line.
func isInstalled(ctx context.Context, eng engine.Engine, container, path string) (bool, error) {
	return engine.Probe(ctx, eng, engine.ExecRequest{
		Container: container,
		Cmd:       engine.Script(`test -x "$1"`, path),
	})
}

// containerArch asks the container, not the host: an Apple-silicon Mac can
// run arm64 or amd64 containers, and only the container's answer matters.
func containerArch(ctx context.Context, eng engine.Engine, container string) (string, error) {
	var out bytes.Buffer
	err := eng.Exec(ctx, engine.ExecRequest{
		Container: container,
		Cmd:       []string{"uname", "-m"},
		Stdout:    &out,
	})
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(out.String()), nil
}

// Scripts that need the toolchain source EnvScript themselves.
func run(ctx context.Context, eng engine.Engine, req Request, script string, args ...string) error {
	return eng.Exec(ctx, engine.ExecRequest{
		Container: req.Container,
		Cmd:       engine.Script(script, args...),
		Stdout:    req.Out,
		Stderr:    req.Out,
	})
}

// Every step is a no-op when its target exists. nvm lives inside the
// directory it manages, so the shared copy is seeded once from the image's
// own and installs go into that — letting a Node outlive the container it was
// installed from.
const provisionScript = `
set -eo pipefail
image_nvm="${NVM_DIR:-/home/frappe/.nvm}"
. ` + EnvScript + `

if [ ! -s "$NVM_DIR/nvm.sh" ]; then
  mkdir -p "$NVM_DIR"
  cp "$image_nvm/nvm.sh" "$image_nvm/nvm-exec" "$NVM_DIR/"
fi
. "$NVM_DIR/nvm.sh"

uv python install "$1"
nvm install "$2"
nvm alias default "$2"

# Asking npm rather than PATH: the bench image ships a yarn of its own, for the
# Node it was built with, and finding that one would leave this Node without.
npm ls --global --depth 0 yarn >/dev/null 2>&1 || npm install --global yarn
`

// envScript renders the sourced file. Regenerated on every create so a tamp
// upgrade that bumps the uv pin takes effect without editing the volume.
func envScript() string {
	return fmt.Sprintf(`# Generated by tamp — do not edit.
#
# Sourced by every command tamp runs in this container, and by the bench's own
# processes. It points Python and Node at the machine-wide shared volume, so
# what one environment installs the next one finds.

export TAMP_TOOLCHAIN=%q
export UV_PYTHON_INSTALL_DIR="$TAMP_TOOLCHAIN/python"
export UV_CACHE_DIR="$TAMP_TOOLCHAIN/uv-cache"
export NVM_DIR="$TAMP_TOOLCHAIN/nvm"
export PATH=%q:"$PATH"

# Puts the default Node on PATH. Absent until the toolchain is provisioned,
# which is the one moment this file is sourced before nvm is there.
if [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"
fi
`, Dir, uvDir())
}

// The bench image's user, at uid 1000 so a Linux host's bind mounts line up
// with the files' owner.
const (
	User = "frappe"
	UID  = 1000
	GID  = 1000
)
