package env

import (
	"os"
	"regexp"
	"slices"
	"strings"
	"testing"

	"github.com/zhide915/tamp/internal/engine/enginetest"
	"github.com/zhide915/tamp/internal/frappe"
	"github.com/zhide915/tamp/internal/syncer"
	"github.com/zhide915/tamp/internal/toolchain"
)

// generated builds an environment and returns its rendered compose.yaml.
func generated(t *testing.T) (*Environment, string) {
	t.Helper()
	return generatedWithSync(t, syncer.UseMutagen)
}

// generatedWithSync varies the sync mode — the one input that changes the
// file's shape.
func generatedWithSync(t *testing.T, sync syncer.Effective) (*Environment, string) {
	t.Helper()
	dir := t.TempDir()
	_, tc, err := ParseFrappeVersion(string(Version15))
	if err != nil {
		t.Fatal(err)
	}
	res, err := NewResources("erp15", dir)
	if err != nil {
		t.Fatal(err)
	}
	e := &Environment{Dir: dir, Config: NewConfig("erp15", Version15, nil, tc, 33061), Resources: res}

	if err := e.Generate(sync); err != nil {
		t.Fatalf("Generate = %v", err)
	}
	body, err := os.ReadFile(ComposePath(dir))
	if err != nil {
		t.Fatal(err)
	}
	return e, string(body)
}

// In tamp's own template, a two-space-indented key under services: is exactly
// a service.
var serviceNames = regexp.MustCompile(`(?m)^  ([a-z][a-z0-9-]*):$`)

func composeServices(t *testing.T, body string) []string {
	t.Helper()
	_, after, ok := strings.Cut(body, "\nservices:\n")
	if !ok {
		t.Fatalf("compose file has no services block:\n%s", body)
	}
	block, _, _ := strings.Cut(after, "\n\n#")
	var names []string
	for _, m := range serviceNames.FindAllStringSubmatch(block, -1) {
		names = append(names, m[1])
	}
	slices.Sort(names)
	return names
}

// Asserted against the fake's service list, so a service added to the
// template without teaching the fake cannot pass unnoticed.
func TestGeneratedComposeDeclaresTheEnvironmentsServices(t *testing.T) {
	_, body := generated(t)

	want := slices.Sorted(slices.Values(enginetest.DefaultServices))
	if got := composeServices(t, body); !slices.Equal(got, want) {
		t.Errorf("services = %v, want %v", got, want)
	}
}

func TestGeneratedComposeSaysItIsGenerated(t *testing.T) {
	_, body := generated(t)

	if !strings.HasPrefix(body, "# Generated by tamp — do not edit.") {
		t.Errorf("compose.yaml does not open with a generated-file warning:\n%s", firstLines(body, 3))
	}
	if !strings.Contains(body, ConfigFile) {
		t.Errorf("compose.yaml does not point at %s as the source of truth", ConfigFile)
	}
}

// Nothing tamp runs may come back by itself after a reboot.
func TestNoServiceHasARestartPolicy(t *testing.T) {
	_, body := generated(t)

	if strings.Contains(body, "restart:") {
		t.Errorf("compose.yaml sets a restart policy:\n%s", body)
	}
}

// Without these flags site creation fails on collation errors.
func TestMariaDBIsConfiguredForFrappesCharacterSet(t *testing.T) {
	_, body := generated(t)

	for _, flag := range []string{
		"--character-set-server=utf8mb4",
		"--collation-server=utf8mb4_unicode_ci",
		"--skip-character-set-client-handshake",
	} {
		if !strings.Contains(body, flag) {
			t.Errorf("compose.yaml does not pass %s to MariaDB", flag)
		}
	}
}

// Bound to loopback: a development database.
func TestOnlyMariaDBPublishesAHostPort(t *testing.T) {
	e, body := generated(t)

	published := regexp.MustCompile(`(?m)^\s+- "([^"]+)"$`)
	var ports []string
	for _, m := range published.FindAllStringSubmatch(body, -1) {
		if strings.Contains(m[1], ":") {
			ports = append(ports, m[1])
		}
	}
	want := []string{"127.0.0.1:33061:3306"}
	if !slices.Equal(ports, want) {
		t.Errorf("published ports = %v, want %v", ports, want)
	}
	if e.Config.Ports.DB != 33061 {
		t.Errorf("the published port did not come from tamp.toml")
	}
}

// Name plus path hash in every resource keeps two environments from
// colliding.
func TestGeneratedComposeNamesTampsResources(t *testing.T) {
	e, body := generated(t)

	for what, name := range map[string]string{
		"project":     e.Resources.Project(),
		"network":     e.Resources.Network(),
		"data volume": e.Resources.Volume(DataVolume),
		"code volume": e.Resources.Volume(CodeVolume),
		"deps volume": e.Resources.Volume(DepsVolume),
		"site volume": e.Resources.Volume(SitesVolume),
	} {
		if !strings.Contains(body, name) {
			t.Errorf("compose.yaml does not name the %s %q", what, name)
		}
	}
}

func TestTheDatabaseCredentialIsNotWrittenIntoTheComposeFile(t *testing.T) {
	e, body := generated(t)

	if err := EnsureDBRootPassword(e.Dir); err != nil {
		t.Fatal(err)
	}
	password, err := os.ReadFile(DBRootPasswordPath(e.Dir))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(body, string(password)) {
		t.Error("compose.yaml contains the database password in clear")
	}
	if !strings.Contains(body, "/run/secrets/"+DBRootPasswordFile) {
		t.Error("compose.yaml does not read the password from the mounted secret")
	}
}

func TestGitignoreCoversTheSecretsAndTheGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	if err := WriteGitignore(dir); err != nil {
		t.Fatal(err)
	}
	body, err := os.ReadFile(dir + "/" + GitignoreFile)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"/" + StateDirName + "/", "/" + ComposeFile} {
		if !strings.Contains(string(body), want) {
			t.Errorf(".gitignore does not exclude %q:\n%s", want, body)
		}
	}
}

// The directory may be the user's own repository, with a .gitignore they
// wrote.
func TestGitignoreIsNotOverwritten(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/" + GitignoreFile
	if err := os.WriteFile(path, []byte("mine\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := WriteGitignore(dir); err != nil {
		t.Fatal(err)
	}
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(body) != "mine\n" {
		t.Errorf(".gitignore = %q, want the user's file untouched", body)
	}
}

// A layer that is not its own volume cannot be cleaned, snapshotted or
// shared.
func TestTheBenchContainerMountsEveryLayerAndTheSharedVolumes(t *testing.T) {
	_, body := generated(t)

	for _, mount := range []string{
		"code:" + frappe.WorkspaceDir,
		"deps:" + frappe.EnvDir,
		"sites:" + frappe.SitesDir,
		"toolchain:" + toolchain.Dir,
		"pip-cache:" + frappe.PipCacheDir,
		"yarn-cache:" + frappe.YarnCacheDir,
		"templates:" + frappe.TemplateDir,
	} {
		if !strings.Contains(body, mount) {
			t.Errorf("the bench container does not mount %s:\n%s", mount, body)
		}
	}
}

// The boot-time check is what lets 'tamp start' revive the processes with
// nothing tamp has to remember.
func TestTheBenchContainerRunsHonchoOnlyOnceThereIsABench(t *testing.T) {
	_, body := generated(t)

	command, _, ok := strings.Cut(body, "working_dir:")
	if !ok {
		t.Fatalf("the bench service has no command:\n%s", body)
	}
	for _, want := range []string{
		"if [ -f " + frappe.ProcfilePath + " ]",
		". " + toolchain.EnvScript,
		"honcho start",
		"sleep infinity",
	} {
		if !strings.Contains(command, want) {
			t.Errorf("the bench command does not contain %q:\n%s", want, command)
		}
	}
}

func firstLines(s string, n int) string {
	lines := strings.SplitN(s, "\n", n+1)
	if len(lines) > n {
		lines = lines[:n]
	}
	return strings.Join(lines, "\n")
}

// The sync modes differ in the compose file by exactly one mount.
func TestGenerateBindsTheHostSourceOnlyInBindMode(t *testing.T) {
	bind := frappe.AppsDir
	if _, body := generatedWithSync(t, syncer.UseBind); !strings.Contains(body, "./"+syncer.AppsDirName+":"+bind) {
		t.Errorf("bind mode did not bind the host's apps directory over %s:\n%s", bind, body)
	}
	if _, body := generatedWithSync(t, syncer.UseMutagen); strings.Contains(body, "./"+syncer.AppsDirName+":") {
		t.Errorf("mutagen mode bound the host's apps directory, which is what it exists to avoid:\n%s", body)
	}
}
