package router

import (
	"fmt"
	"slices"
	"strings"
)

// Env is an environment reduced to routing facts; the caller resolves
// registry and bench details and hands over addresses.
type Env struct {
	Name string
	// Network is the environment's private Docker network.
	Network string
	// Web and Socket are the bench's two upstreams (host:port on Network):
	// Frappe serves HTTP and socket.io on separate ports, so each site needs
	// two routes.
	Web, Socket string
	// Mail is the mail UI upstream, host:port on Network.
	Mail string
	// Sites are hostnames. Frappe resolves the site from the Host header, so
	// the header must pass through — which Caddy does by default.
	Sites []string
}

// MailHost is the mail UI hostname; *.localhost resolves in browsers with no
// configuration.
func MailHost(env string) string { return "mail." + env + ".localhost" }

const caddyfileHeader = `# Generated by tamp — do not edit.
#
# tamp reassembles this file from its registry of environments whenever an
# environment or a site changes, and reloads the router container with it.
`

// Caddyfile assembles every environment's routes at once, so the output never
// depends on which environments are running: a stopped one keeps its routes.
func Caddyfile(envs []Env) string {
	var b strings.Builder
	b.WriteString(caddyfileHeader)

	// Unrouted hostnames get an explanation instead of Caddy's empty response.
	fmt.Fprintf(&b, `
:%d {
	respond "tamp: no site or mail UI is routed at this hostname" 404
}
`, ListenPort)

	for _, e := range envs {
		fmt.Fprintf(&b, "\n# %s\n", e.Name)
		fmt.Fprintf(&b, "http://%s {\n\treverse_proxy %s\n}\n", MailHost(e.Name), e.Mail)

		for _, site := range slices.Sorted(slices.Values(e.Sites)) {
			// socket.io must go to its own port or the desk loses live
			// updates.
			fmt.Fprintf(&b, "\nhttp://%s {\n", site)
			b.WriteString("\t@socketio path /socket.io /socket.io/*\n")
			fmt.Fprintf(&b, "\treverse_proxy @socketio %s\n", e.Socket)
			fmt.Fprintf(&b, "\treverse_proxy %s\n}\n", e.Web)
		}
	}
	return b.String()
}
