package router

import (
	"fmt"
	"slices"
	"strings"
)

// Env is one environment, as the router needs to know it.
//
// It is tamp's environment reduced to routing facts, so that this package
// knows nothing about tamp.toml, the registry or the bench — the caller
// resolves all of that and hands over the addresses.
type Env struct {
	// Name is the environment's name. The mail UI is at mail.<name>.localhost.
	Name string
	// Network is the environment's private Docker network. The router reaches
	// nothing inside the environment until it is attached to it.
	Network string
	// Web and Socket are the bench's two upstreams, as host:port on Network.
	// Frappe serves the site on one and socket.io on the other, which is why
	// one site needs two routes rather than one.
	Web, Socket string
	// Mail is the environment's mail UI upstream, as host:port on Network.
	Mail string
	// Sites are the environment's site hostnames. Frappe resolves the site
	// from the Host header, so a site's hostname is its route and its name at
	// once — which is also why the router must pass the header through, as
	// Caddy does by default.
	Sites []string
}

// MailHost is where an environment's mail UI is reached. Every mail a site
// sends lands there, and *.localhost needs no configuration in any evergreen
// browser — which is what makes it reachable the moment the environment exists.
func MailHost(env string) string { return "mail." + env + ".localhost" }

// caddyfileHeader opens the assembled file. It says the two things someone who
// found this file by accident needs: tamp wrote it, and editing it is futile.
const caddyfileHeader = `# Generated by tamp — do not edit.
#
# tamp reassembles this file from its registry of environments whenever an
# environment or a site changes, and reloads the router container with it.
`

// Caddyfile assembles every environment's routes into the one configuration
// the router serves.
//
// It takes all the environments at once, rather than merging per-environment
// snippets, because that is what makes the result independent of which
// environments happen to be running: an environment that is stopped keeps its
// routes, so stopping one never takes another's away.
func Caddyfile(envs []Env) string {
	var b strings.Builder
	b.WriteString(caddyfileHeader)

	// Every hostname tamp does not route. Without it a browser pointed at the
	// router gets Caddy's own empty response, which says nothing about why the
	// site is not there.
	fmt.Fprintf(&b, `
:%d {
	respond "tamp: no site or mail UI is routed at this hostname" 404
}
`, ListenPort)

	for _, e := range envs {
		fmt.Fprintf(&b, "\n# %s\n", e.Name)
		fmt.Fprintf(&b, "http://%s {\n\treverse_proxy %s\n}\n", MailHost(e.Name), e.Mail)

		for _, site := range slices.Sorted(slices.Values(e.Sites)) {
			// socket.io is a second server on a second port, and the desk
			// stops updating in real time if it is not split out.
			fmt.Fprintf(&b, "\nhttp://%s {\n", site)
			b.WriteString("\t@socketio path /socket.io /socket.io/*\n")
			fmt.Fprintf(&b, "\treverse_proxy @socketio %s\n", e.Socket)
			fmt.Fprintf(&b, "\treverse_proxy %s\n}\n", e.Web)
		}
	}
	return b.String()
}
